name: Arweave Deploy

on:
  push:
    branches:
      - master

jobs:
  Arweave-build-and-deploy:
    runs-on: ubuntu-latest
    env:
      VITE_GA4_MEASUREMENT_ID: ${{ vars.GA4_MEASUREMENT_ID }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Sanity: required configs
      - name: Check required configurations
        run: |
          if [ -z "$DEPLOY_KEY" ]; then
            echo "Error: DEPLOY_KEY secret is required but not set"
            exit 1
          fi
          if [ -z "$DEPLOY_ARNS_NAME" ]; then
            echo "Error: DEPLOY_ARNS_NAME variable is required but not set"
            exit 1
          fi
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          DEPLOY_ARNS_NAME: ${{ vars.DEPLOY_ARNS_NAME }}

      # ---- Build APP (root) ----
      - name: Install app deps & build
        run: |
          npm ci
          npm run build   # must output to ./dist

      # ---- Build DOCS (Docusaurus in ./website) ----
      - name: Install docs deps & build
        working-directory: ./website
        run: |
          npm ci
          npm run build   # outputs ./website/build

      # ---- Merge docs into app artifact under /docs ----
      - name: Assemble final artifact
        run: |
          mkdir -p dist/docs
          cp -r website/build/* dist/docs/
          echo "Final artifact ready at ./dist (app) + ./dist/docs (docs)"

      # ---- Deploy (no undername) ----
      - name: Deploy without undername
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          DEPLOY_ARNS_NAME: ${{ vars.DEPLOY_ARNS_NAME }}
        run: |
          echo "Deploying without undername to base ArNS"
          npm run deploy
